---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: demo-cron
  namespace: demo
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      labels: null
      cron-job: demo-cron
    spec:
      template:
        spec:
          containers:
            - name: demo-cron
              image: busybox:latest
              command:
                - /bin/sh
                - -c
                - Job complete!
